apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: problem-service
type: Opaque
stringData:
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  POSTGRES_DB: ${DB_NAME}
