apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: problem-service
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
